# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

api_v1:
    resource:
        path: ../src/Controller/Api/V1
        namespace: App\Controller\Api\V1
    type: attribute
    prefix: /api/v1
    name_prefix: api_v1_

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: ../src/Controller/Api/V1

api_login_check:
    path: /api/v1/auth/login
api_refresh_token:
    path: /api/v1/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh